# Basic Feasible Solutions

## Basic Solutions {.smaller}

:::: {.columns}

::: {.column width="55%"}

::: {.callout-note icon=false}
## System of equalities 
$$ \bm{Ax} = \bm{b} $$ {#eq-sys}

* From the $n$ columns of $\bm{A}$, we select a set of $m$ linearly independent
columns.
* WLOG, assume that the first $m$ columns of $\bm{A}$ are selected: denote the
$m \times m$ matrix determined by these columns by $\bm{B}$.
* The matrix $\bm{B}$ is nonsingular and we may uniquely solve the equation
$$ \bm{Bx_B} = \bm{b} \quad \text{or} \quad \bm{x_B} = \bm{B}^{-1}\bm{b} $$
:::

* We refer to $\bm{B}$ as a basis, since $\bm{B}$ consists of $m$ linearly
independent columns that can be regarded as a basis for $\mathbb{R}^m$.


:::

::: {.column width="45%"}

::: {.callout-tip icon=false}
## Definition
Given the set of $m$ simultaneous linear equations $n$ unknowns @eq-sys, let
$\bm{B}$ be any nonsingular $m \times m$ submatrix made up of columns of
$\bm{A}$. Then, if all $n-m$ components of $\bm{x}$ not associated with columns
of $\bm{B}$ are set equal to zero, the solution to the resulting set of
equations is said to be a _basic solution_ to @eq-sys with respect to basis
$\bm{B}$.
:::


::: {.callout-tip icon=false}
## Definition
The components of $\bm{x}$ associated with the columns of $\bm{B}$, denoted by
the subvector $\bm{x}_B$ according to the same column index order in $\bm{B}$,
are called _basic variables_.
:::

:::

::::

::: {.callout-warning icon=false}
## Full-Rank Assumption
The $m \times n$ matrix $\bm{A}$ has $m < n$, and the $m$ rows of $\bm{A}$ are
_linearly independent_.
:::


## Basic Feasible Solutions {.smaller}

::: {.callout-tip icon=false}
## Definition
If one or more of the basic variables in a basic solution has value zero, that
solution is said to be a _degenerate basic solution_.
:::

* In a nondegenerate basic solution, the basic variables, and hence the basis
$\bm{B}$, can be immediately identified from the positive components of the
solution.
  - There is ambiguity associated with a degenerate basic solution &ndash; some
    of the nonbasic variables can be interchanged!

::: {.callout-tip icon=false}
## Definition
A vector $\bm{x}$ satisfying 

$$
\bm{Ax} = \bm{b}, \quad \bm{x} \geq \bm{0},
$$ {#eq-fullcon}

is said to be _feasible_ for these constraints. A feasible solution to the
constraints @eq-fullcon that is also basic is said to be a _basic feasible
solution_; if this solution is also a degenerate basic solution, it is called a
_degenerate basic feasible solution_.
:::
