# Farkas's Lemma and Alternative Systems

## (In)feasibility Certificates

::: {.callout-tip icon=false}
## Theorem (Farkas's Lemma).
Let $\bm{A}$ be an $m \times n$ matrix and $\bm{b}$ be an $m$-vector. The system
of constraints 
$$ \bm{Ax} = \bm{b}, \quad \bm{x} \geq \bm{0} $$ {#eq-p7}
has a feasible solution $\bm{x}$ if and only if the system of constraints 
$$ -\bm{y}^\top \bm{A} \geq \bm{0}, \quad \bm{y}^\top \bm{b} = 1 (\text{or} > 0)
$$ {#eq-p8}
has no feasible solution $\bm{y}$. Therefore a single feasible solution $\bm{y}$
for system @eq-p8 establishes an infeasibility certificate for the system
@eq-p7.
:::

* The two systems, @eq-p7 and @eq-p8, are called alternative systems: one of
them is feasible and the other is infeasible.

::: {.callout-important icon=false}
## Example 1
Suppose $\bm{A} = \begin{bmatrix} 1 & 1 \end{bmatrix}, \quad \bm{b} = -1$.
Then, $y = -1$ is feasible for system @eq-p8, which proves that the system
@eq-p7 is infeasible.
:::


## (In)feasibility Certificates {.smaller}

::: {.callout-tip icon=false}
## Lemma
Let $C$ be the cone generated by the columns of matrix $\bm{A}$, that is 
$$ C = \{\bm{Ax} \in \mathbb{R}^m: \bm{x} \geq \bm{0}\}. $$ Then C is a closed
and convex set.
:::

::: {.callout-note icon=false}
## Proof (of Farkas's Lemma).
Let the system @eq-p7 have a feasible solution, say $\bar{\bm{x}}$. Then, the
system @eq-p8 must be infeasible, since, otherwise, we have a contradiction

$$ 0 < \bm{y}^\top \bm{b} = \bm{y}^\top(\bm{A}\bar{\bm{x}}) = (\bm{y}^\top
\bm{A})\bar{\bm{x}} \leq 0, $$

from $\bar{\bm{x}} \geq \bm{0}$ and $\bm{y}^\top \bm{A} \leq \bm{0}$.

Now, let the system @eq-p7 have no feasible solution, that is, $\bm{b} \notin C
:= \{\bm{Ax}: \bm{x} \geq 0\}$. We now prove that its alternative system @eq-p8
must have a feasible solution.

Since points $\bm{b}$ is not in $C$ and $C$ is a closed convex set, by the
separating hyperplane theorem, there is a $\bm{y}$ such that $$ \bm{y}^\top
\bm{b} > \operatorname{sup}_{\bm{c} \in C} \bm{y}^\top \bm{c}. $$ But we know
that $\bm{c} = \bm{Ax}$ for some $\bm{x} \geq \bm{0}$, so we have
$$ \bm{y}^\top \bm{b} > \operatorname{sup}_{\bm{x}\geq\bm{0}} \bm{y}^\top
\bm{Ax} = \operatorname{sup}_{\bm{x} \geq \bm{0}} (\bm{y}^\top \bm{A})\bm{x}. $$ {#eq-p9}
Setting $\bm{x} = \bm{0}$, we have $\bm{y}^\top \bm{b} > 0$ from inequality
@eq-p9.
:::


## (In)feasibility Certificates {.smaller}

::: {.callout-note icon=false}
## Proof (of Farkas's Lemma) - Continued -
Furthermore, inequality @eq-p9 also implies $\bm{y}^\top \bm{A} \leq \bm{0}$.
Since otherwise, say the first entry of $\bm{y}^\top \bm{A}$, $(\bm{y}^\top
\bm{A})_1$, is positive. We can then choose a vector $\bar{\bm{x}} \geq \bm{0}$
such that 

$$ \bar{x}_1 = \alpha > 0, \bar{x}_2 = \cdots = \bar{x}_n = 0. $$

Then, from this choice, we have

$$ \operatorname{sup}_{\bm{x} \geq \bm{0}} (\bm{y}^\top\bm{A})\bm{x} \geq
(\bm{y}^\top \bm{A})\bar{\bm{x}} = \alpha(\bm{y}^\top \bm{A})_1. $$

This tends to $\infty$ as $\alpha \rightarrow \infty$. This is a contradiction
because $(\bm{y}^\top\bm{A})\bar{\bm{x}}$ should be bounded from above by
inequality @eq-p9. Therefore, $\bm{y}$ identified in the separating hyperplane
theorem is a feasible solution to system @eq-p8. Finally, we can always scale
$\bm{y}$ such that $\bm{y}^\top \bm{b} = 1$.
:::


::: {.callout-important icon=false}
## Geometric Interpretation
If $\bm{b}$ is not in the _closed and convex cone_ generated by the columns of
the matrix $\bm{A}$, then there must be a hyperplane separating $\bm{b}$ and the
cone, and the feasible solution $\bm{y}$ to the alternative system is the
slope-vector of the hyperplane.
:::


## Variant of Farkas's Lemma

::: {.callout-tip icon=false}
## Corollary
Let $\bm{A}$ be an $m \times n$ matrix and $\bm{c}$ an $n$-vector. The system of
constraints 

$$ \bm{A}^\top \bm{y} \leq c $$ {#eq-p10}

has a feasible solution $\bm{y}$ if and only if the system of constraints

$$ \bm{Ax} = \bm{0}, \quad \bm{x} \geq \bm{0}, \quad \bm{c}^\top \bm{x} = -1 \;
(\text{or} < 0) $$ {#eq-p11}

has no feasible solution $\bm{x}$. Therefore a single feasible solution $\bm{x}$
for system @eq-p11 establishes an infeasibility certificate for the system
@eq-p10.
:::
